Description: 'Template to generate the necessary IAM Policies for Jenkins-X EKS support '
Resources:
  CFNCertManagerPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join [ "-", [ CFNCertManagerPolicy, Ref: PoliciesSuffixParameter] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - route53:GetChange
          Resource: "arn:aws:route53:::change/*"
        - Effect: Allow
          Action:
          - route53:ChangeResourceRecordSets
          Resource: "arn:aws:route53:::hostedzone/*"
        - Effect: Allow
          Action:
          - route53:ListHostedZonesByName
          Resource: "*"
Parameters:
  PoliciesSuffixParameter:
    Type: String
    Description: A suffix so we can create different policies on each execution
Outputs:
  CFNCertManagerPolicy:
    Value:
      Ref: CFNCertManagerPolicies
    Description: The ARN of the created policy
    Export:
      Name: !Join [ "-", [ CertManagerPolicy, Ref: PoliciesSuffixParameter] ]
